### ISSUE TITLE
Programmatically collapsing a box

### ISSUE THREAD

**Issue by sunitk** [onokumus/Bootstrap-Admin-Template#51]
How can one collapse or close a box widget?

Currently you have to click on the minus icon in the top right of the box widget.

**Comment by onokumus** [comment]
@sunitk 
see https://github.com/onokumus/Bootstrap-Admin-Template/blob/master/src/assets/js/core/fullscreen.js#L30

see https://github.com/onokumus/Bootstrap-Admin-Template/blob/master/src/assets/js/core/fullscreen.js#L59
