### ISSUE TITLE
when i run common "npm install" ,display error ,how to fix?

### ISSUE THREAD

**Issue by kobeng** [onokumus/Bootstrap-Admin-Template#62]
22250 error Error: ENOENT, lstat '/home/kobeng_new/tmp/npm-11496-KkohcYj5/1430061468033-0.7947650256101042/package/README.md'
22251 error If you need help, you may report this log at:
22251 error     <http://github.com/isaacs/npm/issues>
22251 error or email it to:
22251 error     <npm-@googlegroups.com>
22252 error System Linux 3.13.0-49-generic
22253 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
22254 error cwd /home/kobeng_new/working/Bootstrap-Admin-Template
22255 error node -v v0.10.25
22256 error npm -v 1.3.10
22257 error path /home/kobeng_new/tmp/npm-11496-KkohcYj5/1430061468033-0.7947650256101042/package/README.md
22258 error fstream_path /home/kobeng_new/tmp/npm-11496-KkohcYj5/1430061468033-0.7947650256101042/package/README.md
22259 error fstream_type File
22260 error fstream_class FileWriter
22261 error code ENOENT
22262 error errno 34
22263 error fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
22263 error fstream_stack Object.oncomplete (fs.js:107:15)
22264 verbose exit [ 34, true ]

**Comment by onokumus** [comment]
@kobeng 
Maybe updating your node & npm version would help you.
