### ISSUE TITLE
multiselect not working

### ISSUE THREAD

**Issue by TojoAntonio** [onokumus/Bootstrap-Admin-Template#65]
Help me, multiselect field not work correctly locally as it appears here: http://demo.onokumus.com/metis/form-general.html

**Comment by onokumus** [comment]
@TojoAntonio 

### Which one does not work?

![multiple_select](https://cloud.githubusercontent.com/assets/742498/8978382/61d5ee62-36aa-11e5-8aef-85f5a4242f45.png)

**Comment by TojoAntonio** [comment]
thanks for your answer!
not work: 2-3-4-5

**Comment by onokumus** [comment]
@TojoAntonio 
Are you trying to make assets work in file or host mode?

**Comment by TojoAntonio** [comment]
I suppose host mode. I followed the building:
    $ git clone https://github.com/onokumus/Bootstrap-Admin-Template.git yourfoldername
    $ cd yourfoldername
    $ npm install
    $ npm run build
    $ grunt serve

**Comment by onokumus** [comment]
@TojoAntonio 
```bash
npm install
bower install
npm run build
grunt serve
```

**Comment by TojoAntonio** [comment]
yes, I've done early

**Comment by onokumus** [comment]
@TojoAntonio 

Ok.

Open form-general.html in dist folder with your favorite editor.
change that following rows:

[#24](https://github.com/onokumus/Bootstrap-Admin-Template/blob/master/dist/form-general.html#L24) 
```html
<link rel="stylesheet" href="assets/lib/jquery-inputlimiter/jquery.inputlimiter.1.0.css">
```
[#2083](https://github.com/onokumus/Bootstrap-Admin-Template/blob/master/dist/form-general.html#L2083)

```html
<script src="assets/lib/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
``` 

[#2084](https://github.com/onokumus/Bootstrap-Admin-Template/blob/master/dist/form-general.html#L2084)

```html
<script src="assets/lib/jQuery.validVal/js/jquery.validVal.min.js"></script>
```

**Comment by TojoAntonio** [comment]
it works!!! thanks a lot!!! (y)
